export const BORROW_BOOK = 'BORROW_BOOK';
export const RETURN_BOOK = 'RETURN_BOOK';
export const POPULATE_INIT_STATE_SUCCEEDED = 'POPULATE_INIT_STATE_SUCCEEDED';
export const POPULATE_INIT_STATE_FAILED = 'POPULATE_INIT_STATE_FAILED';
